spring.application.name=order-service
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/order-service
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update

#server.address=0.0.0.0
server.port=8081
api.base-url=/api/

external.apis.inventory-service.url=https://localhost:8082/api
external.apis.inventory-product.url=https://localhost:8080/api