spring.application.name=product-service
spring.data.mongodb.uri=mongodb://localhost:27017/product-service
spring.data.mongodb.connection-timeout=30000
spring.data.mongodb.socket-timeout=30000


external.apis.inventory-service.url=https://localhost:8082/api
external.apis.order-service.url=https://localhost:8081/api
